name: CI
on:
  workflow_dispatch:
    inputs:
      link:
        required: true
      name:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download
        run: |
          mkdir /home/runner/download && cd /home/runner/download
          ${{ inputs.link }}
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.name }}
          name: ${{ inputs.name }}
          body: Download
          draft: false
          prerelease: false
          files: /home/runner/download/*
